name: geocoding_assistant
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.6
  flutter_typeahead: ^4.0.0
  autocomplete_textfield: ^2.0.1
  shared_preferences: ^2.0.11
  google_maps_flutter: ^2.6.1
  google_maps_flutter_web: ^0.5.7
  http: ^1.2.1
  location: ^6.0.2
  url_launcher: ^6.0.17
  fluttertoast: ^8.0.8
  share: ^2.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.0.5+1
  flutter_lints: ^3.0.0
  

flutter:
  uses-material-design: true
  assets:
    - assets/icon/gen2.png

flutter_native_splash:
    color: "#bababb"
    image: assets/icon/gen2.png
    android: true
    ios: true
